version: "3.2"
services:
  db:
    image: mongo:4.4-bionic
    ports:
      - "127.0.0.1:2${SEALIOUS_PORT:-0723}:27017"
  test:
    image: sealious-test:latest
    build:
      context: .
      dockerfile: test.dockerfile
    volumes:
      - ./:/opt/sealious/
    ports:
      - "127.0.0.1:${SEALIOUS_PORT:-8080}:${SEALIOUS_PORT:-8080}"
    user: ${UID:-1000}:${GID:-1000}
  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "127.0.0.1:1080:1080"
      - "127.0.0.1:1025:1025"